-- Space Age Extended -- runtime.
--
-- Deliberately near-empty by design: everything in the mod is expressed in
-- prototypes. The one exception, arriving with Phase 4, is the win condition:
-- vanilla's Solar System Edge victory is disabled at init through
-- space_finish_script's set_no_victory, and the mod calls game.set_game_state
-- itself when the Ignition Array fires.
