-- Space Age Extended -- data stage.
--
-- Deliberately empty. The mod is being rebuilt to the design in design/;
-- prototypes arrive with Phase 1 (the Core as a place). See
-- design/05-roadmap.md for what lands when.
