-- Reserved for edits to vanilla prototypes.
--
-- The design's rule is that the mod adds and does not alter, so this file
-- should stay empty. The single deliberate exception -- moving the win
-- condition -- is a runtime change in control.lua, not a prototype one.
