#!/usr/bin/env python3
"""Fire a filled-in building spec's image prompts at OpenAI's image API.

The spec documents in graphics/ carry their generation prompts in fenced
```text blocks under known headings (see building-spec-template.md §11 and
§16). This reads those blocks straight out of the markdown, so the prompts
that get generated are always the prompts in the document -- there is no
second copy to drift.

DALL-E 2 and 3 are retired; their successor is the gpt-image-* family, which
is what --model defaults to. Transparent backgrounds are requested directly,
so no magenta keying step is needed.

Attachments are supported: `--attach` puts reference images in front of the
generator and switches to the /images/edits endpoint, which is what the option
rounds needed a browser for until now. See each `*-options/README.md` for what
to attach and why the order matters.

Usage:
  tools/generate-building-art.py graphics/building-spec-vent-pump.md
  tools/generate-building-art.py graphics/drop-crusher-options/A-*.md \
      --attach ref/assembling-machine-3.png --attach ref/foundry.png \
      --tag A --outdir graphics/entity/drop-crusher/concept/options
  tools/generate-building-art.py <spec> --only master,icon
  tools/generate-building-art.py <spec> --list
  tools/generate-building-art.py <spec> --tag v2 --quality medium

Output lands in graphics/entity/<building>/concept/<tag>-<slug>.png.
Needs an OpenAI key in OPEN_API_KEY (or OPENAI_API_KEY).
"""

import argparse
import base64
import json
import os
import re
import sys
import urllib.error
import urllib.request

API = "https://api.openai.com/v1/images/generations"
# The same family, but the endpoint that accepts reference images. Every round in
# this repo attaches vanilla sprites so the generator has the game's camera and
# finish in front of it rather than a paragraph describing them -- see
# tools/extract-style-references.py, and the "What to attach, every time" table
# in each `*-options/README.md`. Until now that could only be done in a browser,
# which is why the option rounds were generated by hand.
EDITS = "https://api.openai.com/v1/images/edits"

# Heading -> output slug. Order is generation order: the concept sheet is
# stage 0 and is approved before anything else is generated.
SECTIONS = [
    ("## Concept Sheet Prompt", "sheet"),
    ("## Master Concept Prompt", "master"),
    ("### North", "north"),
    ("### East", "east"),
    ("### South", "south"),
    ("### West", "west"),
    ("### Main Structure", "layer-structure"),
    ("### Working Machinery", "layer-machinery"),
    ("### Glow / Lighting", "layer-glow"),
    ("### Effects", "layer-effects"),
    ("### Icon Prompt", "icon"),
]

MASTER_REF = re.compile(r"\[Master prompt\]\s*", re.I)
SKIP = re.compile(r"^\s*(not required|do not generate)", re.I)


def blocks(spec_text):
    """Pull the first ```text fence following each known heading."""
    found = {}
    for heading, slug in SECTIONS:
        # Whole-line match. A prefix match would let "### Effects" bind to
        # "### Effects this building must never show, and why" in section 10
        # and pull the wrong fence.
        m = re.search(r"^" + re.escape(heading) + r"\s*$",
                      spec_text, re.M)
        if not m:
            continue
        i = m.start()
        m = re.search(r"```text\n(.*?)```", spec_text[i:], re.S)
        if not m:
            continue
        body = m.group(1).strip()
        if SKIP.match(body) or not body:
            continue
        found[slug] = body
    return found


def expand(prompts):
    """Splice the master prompt into the ones that reference it."""
    master = prompts.get("master")
    out = {}
    for slug, body in prompts.items():
        if slug != "master" and MASTER_REF.search(body):
            if not master:
                sys.exit(f"{slug} references [Master prompt] but none was found")
            body = MASTER_REF.sub("", body).strip()
            body = master + "\n\n" + body
        out[slug] = body
    return out


def multipart(fields, files):
    """Encode a multipart/form-data body with the standard library.

    `requests` would do this in a line, and this repo's tools take no
    dependencies it can avoid -- everything else here runs on urllib.

    Reference images go over as repeated `image[]` parts. The order is the order
    they are named on the command line, and it matters: the model weights the
    first attachment most, so the house camera goes first and the format example
    last.
    """
    boundary = "----sae" + base64.urlsafe_b64encode(os.urandom(18)).decode()
    body = bytearray()
    for key, value in fields:
        body += (f"--{boundary}\r\n"
                 f'Content-Disposition: form-data; name="{key}"\r\n\r\n'
                 f"{value}\r\n").encode()
    for key, path in files:
        filename = os.path.basename(path)
        body += (f"--{boundary}\r\n"
                 f'Content-Disposition: form-data; name="{key}"; '
                 f'filename="{filename}"\r\n'
                 f"Content-Type: image/png\r\n\r\n").encode()
        with open(path, "rb") as fh:
            body += fh.read()
        body += b"\r\n"
    body += f"--{boundary}--\r\n".encode()
    return bytes(body), "multipart/form-data; boundary=" + boundary


def generate(key, model, prompt, size, quality, background, attach=()):
    """One image. With attachments this goes to /images/edits, without to
    /images/generations -- they are different endpoints with different bodies,
    and only the first one takes reference images."""
    if attach:
        fields = [("model", model), ("prompt", prompt), ("n", "1"),
                  ("size", size), ("quality", quality)]
        # `background` is rejected by the edits endpoint for some model/size
        # combinations, and a concept sheet wants an opaque background anyway --
        # it is a page, not a sprite. Only pass it when it was asked for.
        if background and background != "transparent":
            fields.append(("background", background))
        data, content_type = multipart(fields, [("image[]", p) for p in attach])
        url = EDITS
    else:
        data = json.dumps({"model": model, "prompt": prompt, "n": 1,
                           "size": size, "quality": quality,
                           "background": background,
                           "output_format": "png"}).encode()
        content_type = "application/json"
        url = API
    req = urllib.request.Request(
        url, data=data,
        headers={"Authorization": "Bearer " + key,
                 "Content-Type": content_type})
    with urllib.request.urlopen(req, timeout=900) as r:
        return json.load(r)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("spec")
    ap.add_argument("--only", help="comma-separated slugs, e.g. master,icon")
    ap.add_argument("--list", action="store_true", help="show slugs and exit")
    ap.add_argument("--tag", default="v1", help="filename prefix (default v1)")
    ap.add_argument("--model", default="gpt-image-2")
    ap.add_argument("--size", default="1024x1024")
    ap.add_argument("--quality", default="high")
    ap.add_argument("--background", default="transparent")
    ap.add_argument("--attach", action="append", default=[], metavar="PNG",
                    help="a reference image to put in front of the generator. "
                         "Repeatable, and ORDER MATTERS -- the first is weighted "
                         "most, so pass the house camera first and the format "
                         "example last. Any attachment switches this to the "
                         "/images/edits endpoint. Cut the vanilla ones with "
                         "tools/extract-style-references.py; they are Wube's "
                         "art, so extract to a scratch directory and never "
                         "commit them.")
    ap.add_argument("--outdir", help="override the output directory. An option "
                                     "round writes to concept/options/ rather "
                                     "than sitting beside the numbered drafts.")
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args()

    repo = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    spec_text = open(args.spec, encoding="utf-8").read()

    name = re.sub(r"^building-spec-|\.md$", "",
                  os.path.basename(args.spec))
    outdir = args.outdir or os.path.join(repo, "graphics", "entity", name,
                                        "concept")

    prompts = expand(blocks(spec_text))
    if args.only:
        want = [s.strip() for s in args.only.split(",")]
        missing = [s for s in want if s not in prompts]
        if missing:
            sys.exit("no such prompt(s) in this spec: " + ", ".join(missing))
        prompts = {s: prompts[s] for s in want}

    if not prompts:
        sys.exit("no ```text prompt blocks found -- is this spec filled in?")

    for path in args.attach:
        if not os.path.isfile(path):
            sys.exit("no such attachment: " + path)

    if args.list or args.dry_run:
        for slug, body in prompts.items():
            print(f"--- {slug}  ({len(body)} chars) -> "
                  f"graphics/entity/{name}/concept/{args.tag}-{slug}.png")
            if args.dry_run:
                print(body + "\n")
        return

    key = os.environ.get("OPEN_API_KEY") or os.environ.get("OPENAI_API_KEY")
    if not key:
        sys.exit("Set OPEN_API_KEY (or OPENAI_API_KEY) first.")

    os.makedirs(outdir, exist_ok=True)
    failed = 0
    for slug, body in prompts.items():
        path = os.path.join(outdir, f"{args.tag}-{slug}.png")
        try:
            data = generate(key, args.model, body, args.size,
                            args.quality, args.background, args.attach)
        except urllib.error.HTTPError as e:
            detail = e.read().decode(errors="replace")
            try:
                detail = json.loads(detail)["error"]["message"]
            except Exception:
                detail = detail[:400]
            print(f"  FAILED  {slug}: HTTP {e.code} -- {detail}", file=sys.stderr)
            failed += 1
            continue
        with open(path, "wb") as f:
            f.write(base64.b64decode(data["data"][0]["b64_json"]))
        usage = data.get("usage") or {}
        print(f"  ok  {slug} -> {os.path.relpath(path, repo)}"
              + (f"  ({usage.get('total_tokens')} tokens)" if usage else ""))

    if failed:
        sys.exit(f"{failed} of {len(prompts)} prompt(s) failed.")
    print(f"Generated {len(prompts)} image(s) into "
          f"graphics/entity/{name}/concept/")


if __name__ == "__main__":
    main()
